export const newsletter = [
  {
    newsletterId: "0",
    title: "나와 어울리는 개발자 유형 찾기",
    hashtag: "#개발자 #mbti #코딩 #프로그래밍",
    writer: "HuemoneLab Co.,Ltd",
    link: "https://mbti.codemate.kr/",
    thumbnail: "https://mbti.codemate.kr/static/media/headerLogo.c5b39579.png",
  },
  {
    newsletterId: "0",
    title: "MBTI 유형별 사랑할 때 특징들",
    hashtag: "#MBTI  #연애 #썸 #플러팅",
    writer: "정보도우미, 살구꿀팁",
    link: "https://socialspeaker.tistory.com/entry/MBTI-%EC%9C%A0%ED%98%95%EB%B3%84-%EC%82%AC%EB%9E%91%ED%95%A0%EB%95%8C-%ED%8A%B9%EC%A7%95%EB%93%A4-%ED%91%9C%ED%98%84%EB%B0%A9%EB%B2%95-%EC%9D%B4%EC%83%81%ED%98%95-%ED%94%8C%EB%9F%AC%ED%8C%85-%EB%A7%A4%EB%A0%A5-%EC%A7%88%ED%88%AC",
    thumbnail:
      "https://blog.kakaocdn.net/dn/2b1Bc/btrnte3s7VN/bqeRKp4qYwcH2Ytt5odxxk/img.jpg",
  },
  // {
  //   newsletterId: "0",
  //   title: "MBTI 아파트에서 생활하는 법",
  //   hashtag: "#아파트 #mbti #부동산",
  //   link: "https://socialspeaker.tistory.com/entry/MBTI-%EC%9C%A0%ED%98%95%EB%B3%84-%EC%95%84%ED%8C%[…]-%EC%83%9D%ED%99%9C%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95",
  //   writer: "살구꿀팁, 정보도우미",
  //   thumbnail: "https://www.16personalities.com/static/images/system/logo.svg",
  // },
  // {
  //   newsletterId: "0",
  //   title: "MBTI 유형별 절대 못하는 것",
  //   hashtag: "#절대불가 #네버 #MBTI #못하는것",
  //   writer: "VISUALDIVE , MBTI알리미",
  //   link: "https://mbti119.tistory.com/entry/MBTI-%EC%9C%A0%ED%98%95%EB%B3%84-%EC%A0%88%EB%8C%80-[…]84%EC%A7%9C-%ED%95%A0-%EC%88%98-%EC%97%86%EB%8A%94%EA%B2%83",
  //   thumbnail: "https://www.16personalities.com/static/images/system/logo.svg",
  // },
  {
    newsletterId: "0",
    title: "재미로 보는 MBTI - 성격유형별 여자친구 특성,ENFJ",
    hashtag: "#여자친구 #ENFJ #성격 #좋은남친어려움",
    writer: "후회없는하루",
    link: "https://post.naver.com/viewer/postView.nhn?volumeNo=31014040&memberNo=7130658",
    thumbnail: "https://post-phinf.pstatic.net/MjAyMTAzMjNfMjk1/MDAxNjE2NDU0MTY4NjMw.mKXObQS-tojSQmkN3-qXF5_iBVrz5-v6T3jj7apLPBcg.41gnqEvBY_dpqi7bJ9lBUhssPzl8dmlRAWbgastTvZIg.JPEG/FB_IMG_1613887920336.jpg?type=w1200",
  },
  // {
  //   newsletterId: "0",
  //   title: "재미로 보는 MBTI - 유형별 여름휴가 준비 모습",
  //   hashtag: "#MBTI #휴가 #여름 #준비",
  //   writer: "정보도우미",
  //   link: "https://socialspeaker.tistory.com/entry/%EC%9E%AC%EB%AF%B8%EB%A1%9C-%EB%B3%B4%EB%8A%94-MB[…]%ED%9C%B4%EA%B0%80-%EC%A4%80%EB%B9%84-%EB%AA%A8%EC%8A%B5",
  //   thumbnail: "https://www.16personalities.com/static/images/system/logo.svg",
  // },
  // {
  //   newsletterId: "0",
  //   title: "MBTI, 유형별 짤",
  //   hashtag: "#MBTI #짤 #유형별",
  //   writer: "살구꿀팁, 정보도우미",
  //   link: "https://socialspeaker.tistory.com/entry/mbti-%EC%9C%A0%ED%98%95-%EB%B3%84-%EA%B0%81%EC%A2[…]%84-%ED%8A%B9%EC%A7%95-mbti-%EC%A7%A4-%EB%AA%A8%EC%9D%8C ",
  //   thumbnail: "https://www.16personalities.com/static/images/system/logo.svg",
  // },
  {
    newsletterId: "0",
    title: "mbti별 수능점수",
    hashtag: "#수능 #입시 #mbti #내신 #수학 #영어 #국어",
    writer: "나무위키",
    link: "https://namu.wiki/w/%EB%8C%80%ED%95%99%EC%88%98%ED%95%99%EB%8A%A5%EB%A0%A5%EC%8B%9C%ED%97%98/MBTI",
    thumbnail: "https://i.namu.wiki/i/jUA1-S0XP6jCUjn8rbiTFBZZ-g_QrJCc-qQe2B2OBJQLhnSMzpqKQYutmGiErDF_egFSGM8D_bD-RRQ7S59wBSUM0E0oOhiJstrzwLmQfEg20qUKvDZeZ7gQOGKGpWwauyOaAjJEw-nAlL-EQereeA.webp",
  },
  {
    newsletterId: "0",
    title: "MBTI 궁합 테스트",
    hashtag: "#궁합 #mbti #운명의상대",
    link: "https://pushoong.com/MBTI/relationship/",
    writer: "인싸놀이터, 푸슝",
    thumbnail: "https://www.notion.so/image/https%3A%2F%2Fd29dbfyawlamz6.cloudfront.net%2Fstatic%2Fimg%2Fpushoong%2Ffavicon_full.47c62592e1aa.png?table=block&id=0ff80304-3f83-4737-b50d-9813e6226eac&cache=v2",
  },
  {
    newsletterId: "0",
    title: "2020 프로그래머스 개발자 MBTI 유형 설문조사 리포트",
    hashtag: "#프로그래머 #MBTI #설문조사 #내친구는과연",
    writer: "프로그래머스",
    link: "https://programmers.co.kr/pages/2020-mbti-survey",
    thumbnail: "https://grepp-cloudfront.s3.ap-northeast-2.amazonaws.com/programmers_imgs/banners/2020-mbti-prgms/mbti_survey-img_sns.png",
  },
  {
    newsletterId: "0",
    title: "MBTI별 직업 추천",
    hashtag: "#MBTI #직업 #추천",
    writer: "인플래닛",
    link: "https://brunch.co.kr/@inplanet/16",
    thumbnail:
      "https://img1.daumcdn.net/thumb/C100x100/?fname=http://t1.daumcdn.net/brunch/service/user/8cso/image/Fz36NsX2EjXMJr5e2oKrc9boFHU.png",
  },
  {
    newsletterId: "0",
    title: "구글, 애플, 나이키의 MBTI",
    hashtag: "#구글 #애플 #나이키 #브랜드 #아키타입",
    writer: "김자유 from 'brunch'",
    link: "https://brunch.co.kr/@thinkaboutlove/224",
    thumbnail:
      "https://blog.printsome.com/wp-content/uploads/Brand-archetypes-infographic-3000x5000.jpg",
  },
  {
    newsletterId: "0",
    title: "MBTI 컨텐츠로 MZ세대 공략하기",
    hashtag: "#MBTI #MZ세대 #컨텐츠",
    writer: "슴씨 피드",
    link: "https://brunch.co.kr/@thesmc/1",
    thumbnail:
      "https://img1.daumcdn.net/thumb/C100x100/?fname=http://t1.daumcdn.net/brunch/service/user/adhh/image/pEEn4DI-Cvngl378_BKUDQBhPNk.png",
  },
  {
    newsletterId: "0",
    title: "banggooso 연애 능력 테스트",
    hashtag: "#MBTI #연애 #데이트",
    writer: "방구석연구소, softsphere",
    link: "https://www.banggooso.com/gl/1002/ ",
    thumbnail:
      "https://cdn.banggooso.com/assets/images/uploadImg/1596642366(M).jpg",
  },
  {
    newsletterId: "0",
    title: "우주 직장인 MBTI",
    hashtag: "#우주 #직장인 #MBTI #플로우 #프롬본부",
    writer: "플로우X프롬본부",
    link: "https://basecamp.from.kr/flow?utm_source=facebook&utm_medium=social&utm_campaign=profile&utm_content=210309_all_BT",
    thumbnail: "https://basecamp.from.kr/_next/image?url=https%3A%2F%2Fcdn.1store.io%2Fbasecamp%2Fimages%2Fhome%2Fmain.png&w=384&q=75",
  },
  {
    newsletterId: "0",
    title: "19금 능력치 테스트",
    hashtag: "#19금 #잠자리 #테스트 #MBTI",
    writer: "Loma/GLAM",
    link: "https://lomastore.com/19types/intro",
    thumbnail: "https://lomastore.com/19types/1f22bbbb8750342d56435009ee30b4da.svg",
  },
  {
    newsletterId: "0",
    title: "돼지유형테스트",
    hashtag: "#MBTI #돼지 #먹방 #음식 #테스트",
    writer: "사윤스튜디오",
    link: "https://pigmbti.sayun.studio/",
    thumbnail: "https://cdn.sayun.studio/pigmbti/images/all.jpg",
  },
  {
    newsletterId: "0",
    title: "mbti가 반반씩 있다면",
    hashtag: "#반반 #중립",
    writer: "텅장주의 카드뉴스",
    link: "https://www.dmitory.com/issue/248205780",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfu-vZEprzpxWclQDHs1ecxLEpJIAP0yvqsuK-CiwVHZFA8xdjGb8Y9NxpwTaiyXJzdoY&usqp=CAU",
  },
  {
    newsletterId: "0",
    title: "MBTI 소개팅",
    hashtag: "#mbti #소개팅 #궁합 #사랑 #아제가바빠서 #연락두절",
    writer: "띵스플로우",
    link: "https://storyplay.com/share/story/HloeSpaeoIlpayHeSp",
    thumbnail:
      "https://storyplay.com/_next/image?url=https%3A%2F%2Fd1n3v67f38xwek.cloudfront.net%2FeyJidWNrZXQiOiJzdG9yeXBsYXktcHJvZCIsImtleSI6IlN0b3J5RmlsZXMvYmExM2FjNzItZTUxMS00NzFhLThiMDUtZWFhY2QzOGQ0MGJiIiwib3V0cHV0Rm9ybWF0IjoicG5nIiwiZWRpdHMiOnsicmVzaXplIjp7InJvdGF0ZSI6bnVsbCwid2lkdGgiOjEwMDAsImhlaWdodCI6MTAwMCwiZml0IjoiaW5zaWRlIn19fQ%3D%3D&w=1920&q=75",
  },
  {
    newsletterId: "0",
    title: "재미로 보는 16가지 MBTI별 여행지 추천",
    hashtag: "#여행 #추천",
    writer: "Travie 강화송 기자",
    link: "https://www.travie.com/news/articleView.html?idxno=50327",
    thumbnail: "https://cdn.travie.com/news/photo/202204/50327_21775_5944.jpg",
  },
  {
    newsletterId: "0",
    title: "한국인이 MBTI를 좋아하는 이유",
    hashtag: "#한국인 #MBTI #좋아하는이유 #성리학",
    writer: "Editor 김성지",
    link: "https://ditoday.com/%ED%95%9C%EA%B5%AD%EC%9D%B8%EC%9D%B4-mbti%EB%A5%BC-%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0/",
    thumbnail:
      "https://ditoday.com/wp-content/uploads/2022/08/MBTI_Reason_Korea-648x365.jpg",
  },
  {
    newsletterId: "0",
    title: "소시오패스 싸이코패스 MBTI에 대해서 알아봐요",
    hashtag: "#소시오패스 #싸이코패스 #MBTI",
    writer: "생각 블로그",
    link: "https://semino.tistory.com/218",
    thumbnail:
      "https://blog.kakaocdn.net/dn/UNFAl/btqV2VJGZUN/CrufwmDWM0gAArpaHs3Hvk/img.png",
  },
  {
    newsletterId: "0",
    title: "MBTI 이상형 테스트",
    hashtag: "#이상형 #MBTI #테스트",
    writer: "Araut",
    link: "https://mbtilovetest.netlify.app/",
    thumbnail: "https://blog.kakaocdn.net/dn/ufbci/btq6pUOiOWq/tFfTkW9W0CvmpKxcaon6L0/img.jpg",
  },
  {
    newsletterId: "0",
    title: "또다시 SNS를 점령한 MBTI?!",
    hashtag: "#타입스 #유퀴즈",
    writer: "고구마팜",
    link: "https://gogumafarm.kr/bbs/board.php?bo_table=article&wr_id=937",
    thumbnail:
      "https://gogumafarm.kr/wp-content/uploads/2023/01/image-1158.png",
  },
  {
    newsletterId: "0",
    title: "mbti보다 더 정확한 테스트",
    hashtag: "#애고그램 #mbti #egogram #성향파악",
    writer: "egogramtest",
    link: "https://egogramtest.kr/",
    thumbnail: "https://d2u3dcdbebyaiu.cloudfront.net/uploads/atch_img/143/2384d58995240f6ba05eeda37f10bf9d_res.jpeg",
  },
  {
    newsletterId: "0",
    title: "거지 되는 MBTI, 부자 되는 MBTI... 따로 있다? ",
    hashtag: "#MBTI #재운 #연예인",
    writer: "오승희, 사이다경제",
    link: "https://cidermics.com/contents/detail/2426",
    thumbnail:
      "https://img.cidermics.com/images/contents/20201218/e6855090-4139-11eb-8597-ef7a4736fdeb.jpg",
  },
  {
    newsletterId: "0",
    title: "MBTI N S 차이 10가지 총정리",
    hashtag: "#NS #mbti #짤 #밈",
    link: "https://ddnews.co.kr/mbti-n-s-%EC%B0%A8%EC%9D%B4/",
    writer: "뚝딱뉴스, 깨비",
    thumbnail:
      "https://ddnews.co.kr/wp-content/uploads/2022/03/MBTI-N-S-차이-4.jpg",
  },
  {
    newsletterId: "0",
    title: "Personality tests become hugely popular among young Koreans",
    hashtag: "#MBTI인기 #해외뉴스",
    writer: "이하린 기자",
    link: "https://www.koreatimes.co.kr/www/nation/2022/08/281_335268.html",
    thumbnail: "https://img.koreatimes.co.kr/upload/newsV2/images/202208/5d5d4687f16647abb112399c19fff83e.jpg/dims/resize/740/optimize",
  },
  {
    newsletterId: "0",
    title: "ENFJ 남자 특징 5가지",
    hashtag: "#ENFJ #남자친구 #이상형 #궁합",
    writer: "뚝딱뉴스",
    link: "https://ddnews.co.kr/enfj-%eb%82%a8%ec%9e%90-%ed%8a%b9%ec%a7%95/#more-10038",
    thumbnail:
      "https://ddnews.co.kr/wp-content/uploads/2022/11/ENFJ-남자-특징-7-1024x611.jpg",
  },
  {
    newsletterId: "0",
    title: "MBTI 궁합",
    hashtag: "#MBTI #궁합 #연애",
    link: "https://ddnews.co.kr/mbti-%EA%B6%81%ED%95%A9%ED%91%9C-%EC%97%B0%EC%95%A0%EA%B6%81%ED%95%A9-%EC%B9%9C%EA%B5%AC%EA%B6%81%ED%95%A9/",
    writer: "뚝딱뉴스, 깨비",
    thumbnail:
      "https://ddnews.co.kr/wp-content/uploads/2021/12/mbti-궁합-3.png",
  },
  {
    newsletterId: "0",
    title: "MBTI & 에니어그램 조합 정리",
    hashtag: "#MBTI, #에니어그램, #Enneagram",
    writer: "노트 주인 from 노트#1",
    link: "https://hobbymemo.tistory.com/576",
    thumbnail:
      "https://blog.kakaocdn.net/dn/bYzeMv/btraXWM5mRZ/DTLUeu4sZgjxzqku9kXB51/img.png",
  },
  {
    newsletterId: "0",
    title: "인생 겜BTI",
    hashtag: "#MBTI #플레이오 #게임 #게임성향 #게임추천",
    writer: "플레이오",
    link: "https://play.playio.kr/mbti",
    thumbnail:
      "https://oopy.lazyrockets.com/api/v2/notion/image?src=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F0fa84812-8302-43bc-bffd-eb521b035ed1%2F%25EC%259D%25B8%25EC%2583%259D%25EA%25B2%259C%25EB%25B9%2584%25ED%258B%25B0%25EC%2595%2584%25EC%259D%25B4.png&blockId=48c179f2-3b84-4256-b4ec-02330afec471&width=3600",
  },
  {
    newsletterId: "0",
    title: "mbti별 범죄를 저지르면 무슨 범죄를 저지를까",
    hashtag: "#mbti #범죄",
    writer: "카스퍼z",
    link: "https://kasper1030.tistory.com/841",
    thumbnail:
      "https://blog.kakaocdn.net/dn/bAlvmU/btrB7cipTra/uUKajQ4YcXyVhSFm6Rs5Yk/img.png",
  },
  {
    newsletterId: "0",
    title: "MBTI 마피아 다이닝",
    hashtag: "#MBTI #소셜다이닝",
    link: "https://fidelio.site/Events/?idx=54",
    writer: "Fidelio",
    thumbnail: "https://cdn.imweb.me/thumbnail/20220225/a4540e01316cd.jpg",
  },
  {
    newsletterId: "0",
    title: "MBTI별 어울리는 직업 추천",
    hashtag: "#직업 #추천 #특징",
    writer: "잡코리아",
    link: "https://www.jobkorea.co.kr/goodjob/tip/view?News_No=18406",
    thumbnail:
      "https://img.jobkorea.co.kr/images/ContentsManagement/SmartEditor/2020/11/2020111715025_SEU.jpg",
  },
  {
    newsletterId: "0",
    title: "ENTP 엔티피 대표연예인 모음 11탄(리정, 한예슬, 이찬혁, 영탁)",
    hashtag: "#MBTI #ENTP #연예인 #리정 #한예슬 #이찬혁 #영탁",
    writer: "고양휘",
    link: "https://master5115.tistory.com/71",
    thumbnail:
      "https://blog.kakaocdn.net/dn/u5zIz/btrox0WMaTH/YKre7iio8I8vjSEebSx4gk/img.png",
  },
  {
    newsletterId: "0",
    title: "태니지먼트",
    hashtag: "#업무 #회사 #회사MBTI",
    writer: "태니지먼트",
    link: "https://blog.tanagement.co.kr/",
    thumbnail: "https://cdn.imweb.me/thumbnail/20220726/9252ec731dceb.png",
  },
  // {
  //   newsletterId: "0",
  //   title: "MBTI 팩폭 모음",
  //   hashtag: "#MBTI #팩폭 #특징",
  //   writer: "뚝딱뉴스 깨비",
  //   link: "https://ddnews.co.kr/mbti-%ED%8C%A9%ED%8F%AD-%EB%AA%A8%EC%9D%8C/",
  //   thumbnail:
  //     "https://ddnews.co.kr/wp-content/uploads/2022/03/MBTI-팩폭-모음-1.jpg",
  // },
  {
    newsletterId: "0",
    title: "MBTI 성격 유형 로맨틱 순위, 연애 스타일 정리",
    hashtag: "#로맨틱 #연애 #mbti",
    writer: "잡앤스토리 J&S",
    link: "https://prism45.tistory.com/300",
    thumbnail:
      "https://tistory1.daumcdn.net/tistory/3947839/attach/64587f8c6f384a85a655c9f339f2bf7f",
  },
  {
    newsletterId: "0",
    title: "MBTI 팩폭 모음 1탄, 2탄 총정리(팩트체크)",
    hashtag: "#팩트 #팩트폭행 #MBTI",
    writer: "뚝딱뉴스",
    link: "https://ddnews.co.kr/mbti-%ED%8C%A9%ED%8F%AD-%EB%AA%A8%EC%9D%8C/",
    thumbnail:
      "https://ddnews.co.kr/wp-content/uploads/2022/03/MBTI-팩폭-모음-1.jpg",
  },
  {
    newsletterId: "0",
    title: "MBTI별 덕질할 때 하기 힘든 행동들",
    hashtag: "#MBTI #덕질 #힘든행동",
    writer: "Pocamarket",
    link: "https://m.facebook.com/pocamarket/photos/pcb.213889257461926/213889197461932/?type=3&source=48&refid=52&__tn__=EH-R",
    thumbnail: "https://scontent-ssn1-1.xx.fbcdn.net/v/t39.30808-6/241392963_213889204128598_6252384128993961808_n.png?_nc_cat=111&ccb=1-7&_nc_sid=730e14&_nc_ohc=lGXEdXtvyOkAX-lvsw-&_nc_ht=scontent-ssn1-1.xx&oh=00_AfD-Cq7HTG3Fxap_r04Inn-SMOfPRGWgLPQ0BkkcZH1Lpg&oe=64184892",
  },
  {
    newsletterId: "0",
    title: "내 MBTI 와 잘 맞는 회사는 어디?",
    hashtag: "#MBTI #취업 #jobplanet #회사 #취준생",
    writer: "Jobplanet",
    link: "https://www.jobplanet.co.kr/contents/news-2848",
    thumbnail:
      "https://jpassets.jobplanet.co.kr/production/uploads/material/media/9098/mbti-%EC%84%B1%EA%B2%A9-%EC%9C%A0%ED%98%95%ED%91%9C4.jpg",
  },
  {
    newsletterId: "0",
    title: "재미로 보는 mbti 순위 총정리",
    hashtag: "#MBTI #순위 #특징",
    writer: "혜빈",
    link: "https://youtu.be/mfQ4fPDYYto",
    thumbnail: "https://i.ytimg.com/an_webp/mfQ4fPDYYto/mqdefault_6s.webp?du=3000&sqp=CIqxyqAG&rs=AOn4CLD9RdArQiH2YeCtTBvF0FR5_l0GDg",
  },
  {
    newsletterId: "0",
    title: "MBTI 경로당/노인정",
    hashtag: "#유튜브 #영상 #만화",
    writer: "에익쿠",
    link: "https://www.youtube.com/watch?v=bQnjZYD-mg4",
    thumbnail: "https://i.ytimg.com/an_webp/bQnjZYD-mg4/mqdefault_6s.webp?du=3000&sqp=CJDAyqAG&rs=AOn4CLBcWk_17VyG9WIjcpAnW8h4x5Q8Yg",
  },
  {
    newsletterId: "0",
    title: "[MBTI 유형별 만화] 48편 - 인간관계와 연애궁합의 차이",
    hashtag: "#MBTI #연애 #궁합 #인간관계",
    writer: "티제월드 TJ world",
    link: "https://youtu.be/9q-B0bOCW1g",
    thumbnail: "https://i.ytimg.com/an_webp/9q-B0bOCW1g/mqdefault_6s.webp?du=3000&sqp=CLDUyqAG&rs=AOn4CLCqYNylpNwuskbGYX9YYd8DSOhlJg",
  },
  {
    newsletterId: "0",
    title: "SBS스페셜 MBTI의 모든 것",
    hashtag: "#SBS스페셜 #교양 #과학",
    writer: "SBS 교양 공식 채널",
    link: "https://youtu.be/j1TxAEFqIRU",
    thumbnail: "https://i.ytimg.com/an_webp/j1TxAEFqIRU/mqdefault_6s.webp?du=3000&sqp=CICDyqAG&rs=AOn4CLCNAXx9XR-COwyKV7DHLu_slLEo2w",
  },
  {
    newsletterId: "0",
    title: "핫트랙스 MBTI 스티커",
    hashtag: "#MBTI, #다이어리꾸미기, #다꾸",
    writer: "핫트랙스",
    link: "https://www.hottracks.co.kr/ht/biz/bizSearchMain",
    thumbnail:
      "//image.kyobobook.co.kr/newimages/giftshop_new/resources/images/pc/kyobo/img_brand_more_kyobo@2x.png",
  },
  {
    newsletterId: "0",
    title:
      "MBTI 유형별 특징 몰아보기 (총 10편) ㅣ 꼬시기 쉬운 MBTI 유형, MBTI별 사랑꾼 순위, 꼬시기 힘든 MBTI 유형 등등",
    hashtag: "#MBTI #사랑꾼 #게으름 #한국인",
    writer: "캘리노트",
    link: "https://youtu.be/KF-4r3qOWGM ",
    thumbnail: "https://i.ytimg.com/an_webp/KF-4r3qOWGM/mqdefault_6s.webp?du=3000&sqp=CL7OyqAG&rs=AOn4CLDmRouMG5QTU9FSJnri7IPlanBkNg",
  },
  {
    newsletterId: "0",
    title: "“INTJ & INTP”의 만남",
    hashtag: "#INTJ #INTP #안소희 #원더걸스 #MBTI",
    writer: "안소희",
    link: "https://www.youtube.com/watch?v=3s5rGYYWR6w&ab_channel=%EC%95%88%EC%86%8C%ED%9D%AC",
    thumbnail: "https://i.ytimg.com/an_webp/3s5rGYYWR6w/mqdefault_6s.webp?du=3000&sqp=CLC1yqAG&rs=AOn4CLDziYKAcd_ATye6Q2IfWa3BUn0d9A",
  },
  {
    newsletterId: "0",
    title: "[두루마리] MBTI I만 모인 메탈밴드. track 1",
    hashtag: "#MBTI #음악 #I #메탈밴드",
    writer: "빵송국",
    link: "https://www.youtube.com/watch?v=W9urHV6-CmA",
    thumbnail: "https://i.ytimg.com/an_webp/W9urHV6-CmA/mqdefault_6s.webp?du=3000&sqp=CKC7yqAG&rs=AOn4CLBs9FAxKApzN-utecAjHb18UNRBOA",
  },
  {
    newsletterId: "0",
    title: "mbti 문항이 과학적으로 증명된 이유",
    hashtag: "#mbti  #심리 #과학적 #증명",
    writer: "assesta",
    link: "https://www.youtube.com/watch?v=ksJnb459Bj4",
    thumbnail: "https://i.ytimg.com/an_webp/ksJnb459Bj4/mqdefault_6s.webp?du=3000&sqp=CLqsyqAG&rs=AOn4CLDYkhriKEbVgrX8eqErneSKkGYlhQ",
  },
  {
    newsletterId: "0",
    title: "메마른 웃음이 난무하는 ISTP들의 밥상머리",
    hashtag: "#박명수 #주우재 #mbti #istp #막걸리",
    writer: "핀트",
    link: "https://www.youtube.com/watch?v=9kCwpSCHhRQ&ab_channel=%ED%95%80%ED%8A%B8",
    thumbnail: "https://i.ytimg.com/an_webp/9kCwpSCHhRQ/mqdefault_6s.webp?du=3000&sqp=CPSVyqAG&rs=AOn4CLApuzWiAkhXBU54d7irEq2yFTwh7g",
  },
  {
    newsletterId: "0",
    title: "ENFP는 누르면 극락갈 플레이리스트(playlist)",
    hashtag: "#ENFP #Playlist #MBTI",
    writer: "손다로우쉬",
    link: "https://www.youtube.com/watch?v=3pthhAiA_6U",
    thumbnail: "https://i.ytimg.com/vi/3pthhAiA_6U/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCD1JqanGcV6UMj-2eMiYK56xmkbw",
  },
  {
    newsletterId: "0",
    title: "유미의 MBTI들 INTP편",
    hashtag: "#강유미 #INTP",
    writer: "강유미 yumi kang 좋아서 하는 채널",
    link: "https://www.youtube.com/watch?v=a50lC2G-6gY&list=PLkzM1g1eTbDHkmyc_zchMLRxm-qDrilsu&index=1",
    thumbnail: "https://i.ytimg.com/an_webp/a50lC2G-6gY/mqdefault_6s.webp?du=3000&sqp=CPaWyqAG&rs=AOn4CLB4tdZqL_2u69AwFDVzQ31uyi9PRA",
  },
  {
    newsletterId: "0",
    title: "MBTI 인사이드",
    hashtag: "#MBTI인사이드 #MBTI하우스 #사회실험",
    writer: "킥더허들스튜디오",
    link: "https://youtu.be/VxnvTBH8yg4",
    thumbnail: "https://i.ytimg.com/an_webp/VxnvTBH8yg4/mqdefault_6s.webp?du=3000&sqp=COyRyqAG&rs=AOn4CLAaG7_ssCIwjNHBQShD_J6SoUQtQA",
  },
  {
    newsletterId: "0",
    title: "일자리 없는 청년 166만명…일하려면 MBTI 내라는 회사들이 나타났다?!",
    hashtag: "#MBTI #비디오머그 #취업",
    writer: "비디오머그",
    link: "https://www.youtube.com/watch?v=wmLKGelGX6s",
    thumbnail: "https://i.ytimg.com/an_webp/wmLKGelGX6s/mqdefault_6s.webp?du=3000&sqp=COa_yqAG&rs=AOn4CLDXyTrU7ue4ntUs_tE6sPtBlLyEEQ",
  },
  {
    newsletterId: "0",
    title: "MBTI 성향별 투자에 성공하는 방법은?",
    hashtag: "#mbti #투자 #투자왕",
    writer: "미래에셋자산운용",
    link: "https://youtu.be/M4H2Hu7X8ps",
    thumbnail: "https://i.ytimg.com/an_webp/M4H2Hu7X8ps/mqdefault_6s.webp?du=3000&sqp=CNHRyqAG&rs=AOn4CLC_YCjOVy0uN6HdbUnngMnZB_uQOA",
  },
  {
    newsletterId: "0",
    title: "INFP에게 먼저 다가가도 될까요? ",
    hashtag: "#유튜브 #인플루엔서 #마마무 #휘인 ",
    writer: "휘인",
    link: "https://youtu.be/3bo_JBVQcEM",
    thumbnail: "https://i.ytimg.com/an_webp/3bo_JBVQcEM/mqdefault_6s.webp?du=3000&sqp=CPubyqAG&rs=AOn4CLAiT14Q4Gm4oKhgfYMsfpP55yOOAA",
  },
  // {
  //   newsletterId: "0",
  //   title: "ISTJ 여자 특징 7가지, 화나게 만드는 4가지",
  //   hashtag: "#ISTJ #여자 #특징 #분노",
  //   writer: "궁금한 심리",
  //   link: "https://mailremember.com/%EC%95%8C%EA%B3%A0-%EB%B3%B4%EB%A9%B4-%EB%86%80%EB%9D%BC%EB%[…]94%EB%82%98%EA%B2%8C-%EB%A7%8C%EB%93%9C%EB%8A%94-4%EA%B0%80/",
  //   thumbnail: "https://www.16personalities.com/static/images/system/logo.svg",
  // },
  {
    newsletterId: "0",
    title: "MBTI 유형별 죽었는지 확인하는 방법",
    hashtag: "#MBTI #MBTI만화 #MBTI일상툰 #죽었는지확인",
    writer: "MBTI일상툰",
    link: "https://www.youtube.com/watch?v=lzq1ZstWAU4&ab_channel=MBTI%EC%9D%BC%EC%83%81%ED%88%B0",
    thumbnail: "https://i.ytimg.com/an_webp/lzq1ZstWAU4/mqdefault_6s.webp?du=3000&sqp=CJyhyqAG&rs=AOn4CLDIWaomdbxB31UWi42K4LlCj5-5HA",
  },
  {
    newsletterId: "0",
    title: "MBTI, 오해와 진실",
    hashtag: "#MBTI #1030 #성격테스트 #오해와진실",
    writer: "중앙일보",
    link: "https://www.youtube.com/watch?v=rZ-x5uNhb4w",
    thumbnail: "https://i.ytimg.com/an_webp/rZ-x5uNhb4w/mqdefault_6s.webp?du=3000&sqp=CLzJyqAG&rs=AOn4CLBkFcodAPoInQO_a_nUQAL-OWDQUg",
  },
  {
    newsletterId: "0",
    title: "MBTI 유형별 헤어지는 이유",
    hashtag: "#MBTI #헤어짐 #연인",
    writer: "MBTI일상툰",
    link: "https://www.youtube.com/watch?v=NneMtQ-yMcc&ab_channel=MBTI%EC%9D%BC%EC%83%81%ED%88%B0",
    thumbnail: "https://i.ytimg.com/an_webp/NneMtQ-yMcc/mqdefault_6s.webp?du=3000&sqp=CLWpyqAG&rs=AOn4CLBn1tTHVxPHSw1exDwFVqzwKoFGpA",
  },
  {
    newsletterId: "0",
    title: "MBTI 유형별 말버릇",
    hashtag: "#MBTI #만화 #일상툰 #유머",
    writer: "MBTI일상툰",
    link: "https://youtu.be/19MpaZMa7Jg",
    thumbnail: "https://i.ytimg.com/an_webp/19MpaZMa7Jg/mqdefault_6s.webp?du=3000&sqp=COjByqAG&rs=AOn4CLDIUDxlt8KPk-4IKSQHOUtRlr2tIg",
  },
];
