export const question = [
{question: "주기적으로 새로운 친구를 만든다.", factor: "EI"},
{question: "자유 시간 중 상당 부분을 다양한 관심사를 탐구하는 데 할애한다.", factor: "NS"},
{question: "다른 사람이 울고 있는 모습을 보면 자신도 울고 싶어질 때가 많다.", factor: "FT"},
{question: "일이 잘못될 때를 대비해 여러 대비책을 세우는 편이다.", factor: "JP"},
{question: "압박감이 심한 환경에서도 평정심을 유지하는 편이다.", factor: "FT"},
{question: "파티나 행사에서 새로운 사람에게 먼저 자신을 소개하기보다는 주로 이미 알고 있는 사람과 대화하는 편이다.", factor: "EI"},
{question: "하나의 프로젝트를 완전히 완료한 후 다른 프로젝트를 시작하는 편이다.", factor: "JP"},
{question: "매우 감상적인 편이다.", factor: "FT"},
{question: "일정이나 목록으로 계획을 세우는 일을 좋아한다.", factor: "JP"},
{question: "작은 실수로도 자신의 능력이나 지식을 의심하곤 한다.", factor: "FT"},
{question: "관심이 가는 사람에게 다가가서 대화를 시작하기가 어렵지 않다.", factor: "EI"},
{question: "예술 작품의 다양한 해석에 대해 토론하는 일에는 크게 관심이 없다.", factor: "NS"},
{question: "감정보다는 이성을 따르는 편이다.", factor: "FT"},
{question: "하루 일정을 계획하기보다는 즉흥적으로 하고 싶은 일을 하는 것을 좋아한다.", factor: "JP"},
{question: "다른 사람에게 자신이 어떤 사람으로 보일지 걱정하지 않는 편이다.", factor: "FT"},
{question: "단체 활동에 참여하는 일을 즐긴다.", factor: "EI"},
{question: "결말을 자신의 방식으로 해석할 수 있는 책과 영화를 좋아한다.", factor: "NS"},
{question: "자신보다는 남의 성공을 돕는 일에서 더 큰 만족감을 느낀다.", factor: "FT"},
{question: "관심사가 너무 많아 다음에 어떤 일을 해야 할지 모를 때가 있다.", factor: "JP"},
{question: "일이 잘못될까봐 자주 걱정하는 편이다.", factor: "FT"},
{question: "단체에서 지도자 역할을 맡는 일은 가능한 피하고 싶다.", factor: "EI"},
{question: "자신에게 예술적 성향이 거의 없다고 생각한다.", factor: "NS"},
{question: "사람들이 감정보다는 이성을 중시했다면 더 나은 세상이 되었으리라고 생각한다.", factor: "FT"},
{question: "휴식을 취하기 전에 집안일을 먼저 끝내기를 원한다.", factor: "JP"},
{question: "다른 사람의 논쟁을 바라보는 일이 즐겁다.", factor: "FT"},
{question: "다른 사람의 주의를 끌지 않으려고 하는 편이다.", factor: "EI"},
{question: "감정이 매우 빠르게 변하곤 한다.", factor: "FT"},
{question: "자신만큼 효율적이지 못한 사람을 보면 짜증이 난다.", factor: "JP"},
{question: "해야 할 일을 마지막까지 미룰 때가 많다.", factor: "JP"},
{question: "사후세계에 대한 질문이 흥미롭다고 생각한다.", factor: "NS"},
{question: "혼자보다는 다른 사람과 시간을 보내고 싶어한다.", factor: "EI"},
{question: "이론 중심의 토론에는 관심이 없으며 원론적인 이야기는 지루하다고 생각한다.", factor: "NS"},
{question: "자신과 배경이 완전히 다른 사람에게도 쉽게 공감할 수 있다.", factor: "FT"},
{question: "결정을 내리는 일을 마지막까지 미루는 편이다.", factor: "JP"},
{question: "이미 내린 결정에 대해서는 다시 생각하지 않는 편이다.", factor: "JP"},
{question: "혼자만의 시간을 보내기보다는 즐거운 파티와 행사로 일주일의 피로를 푸는 편이다.", factor: "EI"},
{question: "미술관에 가는 일을 좋아한다.", factor: "NS"},
{question: "다른 사람의 감정을 이해하기 힘들 때가 많다.", factor: "FT"},
{question: "매일 할 일을 계획하는 일을 좋아한다.", factor: "JP"},
{question: "불안함을 느낄 때가 거의 없다.", factor: "FT"},
{question: "전화 통화를 거는 일은 가능한 피하고 싶다.", factor: "EI"},
{question: "자신의 의견과 매우 다른 의견을 이해하기 위해 많은 시간을 할애하곤 한다.", factor: "FT"},
{question: "친구에게 먼저 만나자고 연락하는 편이다.", factor: "EI"},
{question: "계획에 차질이 생기면 최대한 빨리 계획으로 돌아가기 위해 노력한다.", factor: "JP"},
{question: "오래전의 실수를 후회할 때가 많다.", factor: "FT"},
{question: "인간의 존재와 삶의 이유에 대해 깊이 생각하지 않는 편이다.", factor: "NS"},
{question: "감정을 조절하기보다는 감정에 휘둘리는 편이다.", factor: "FT"},
{question: "상대방의 잘못이라는 것이 명백할 때도 상대방의 체면을 살려주기 위해 노력한다.", factor: "FT"},
{question: "계획에 따라 일관성 있게 업무를 진행하기보다는 즉흥적인 에너지로 업무를 몰아서 처리하는 편이다.", factor: "JP"},
{question: "상대방이 자신을 높게 평가하면 나중에 상대방이 실망하게 될까 걱정하곤 한다.", factor: "FT"},
{question: "대부분의 시간을 혼자서 일할 수 있는 직업을 원한다.", factor: "EI"},
{question: "철학적인 질문에 대해 깊게 생각하는 일은 시간 낭비라고 생각한다.", factor: "NS"},
{question: "조용하고 사적인 장소보다는 사람들로 붐비고 떠들썩한 장소를 좋아한다.", factor: "EI"},
{question: "상대방의 감정을 바로 알아차릴 수 있다.", factor: "FT"},
{question: "무엇인가에 압도당하는 기분을 느낄 때가 많다.", factor: "FT"},
{question: "단계를 건너뛰는 일 없이 절차대로 일을 완수하는 편이다.", factor: "JP"},
{question: "논란이 되거나 논쟁을 불러일으킬 수 있는 주제에 관심이많다.", factor: "NS"},
{question: "자신보다 다른 사람에게 더 필요한 기회라고 생각되면 기회를 포기할 수도 있다.", factor: "FT"},
{question: "마감 기한을 지키기가 힘들다.", factor: "JP"},
{question: "일이 원하는 대로 진행될 것이라는 자신감이 있다.", factor: "FT"},
{question: "사회적 상황에서 주로 이야기 주체가 되는 편이다.", factor: "EI"},
{question: "혼자만의 시간을 보내는 것보다 다른 사람들과 함께하는 것을 선호한다.", factor: "EI"},
{question: "새로운 사람들과 쉽게 친해지는 편이다.", factor: "EI"},
{question: "활발한 환경에서 에너지를 얻는 것 같다.", factor: "EI"},
{question: "다른 사람들과 대화하는 것이 힘든 일이 아니다.", factor: "EI"},
{question: "크게 소리내어 웃을 때가 많다.", factor: "EI"},
{question: "주변 사람들과 의견을 나누는 것을 즐긴다.", factor: "EI"},
{question: "친구들과의 파티나 모임에 적극적으로 참여하는 편이다.", factor: "EI"},
{question: "혼자 공부하는 것보다 다른 사람들과 함께 공부하는 것을 선호한다.", factor: "EI"},
{question: "사람들이 모여있는 곳에서 더 기분이 좋아진다.", factor: "EI"},
{question: "새로운 아이디어나 발상을 즐기며 창의적인 생각을 선호한다.", factor: "NS"},
{question: "평범한 일상보다는 다양한 경험을 추구하는 편이다.", factor: "NS"},
{question: "빠르게 변화하는 환경에 적응하는 능력이 뛰어나다.", factor: "NS"},
{question: "복잡한 문제를 해결하는 과정에서 즐거움을 느낀다.", factor: "NS"},
{question: "새로운 관점을 찾아내는 것에 흥미를 느낀다.", factor: "NS"},
{question: "기존의 방식을 벗어나 새로운 접근법을 시도하는 것을 좋아한다.", factor: "NS"},
{question: "개방적이고 호기심이 많아 새로운 정보를 학습하는 것에 열정적이다.", factor: "NS"},
{question: "일상적인 일에 대해 새로운 시각을 갖고 생각하는 편이다.", factor: "NS"},
{question: "추상적인 개념과 이론에 대해 관심이 많고 탐구하는 것을 즐긴다.", factor: "NS"},
{question: "실험적인 아이디어를 도전하는 것에 두려움이 없다.", factor: "NS"},
{question: "자주 다른 사람의 감정 상태를 고려하여 대화를 진행한다.", factor: "FT"},
{question: "타인의 감정에 공감하고 그들을 위로하는 것이 자연스러운 편이다.", factor: "FT"},
{question: "누군가에게 도움이 필요할 때, 이성적인 판단보다 감정에 기반한 결정을 선호한다.", factor: "FT"},
{question: "다양한 사람들과 깊이 있는 대화를 나누는 것을 즐긴다.", factor: "FT"},
{question: "자신의 감정을 잘 이해하고 표현할 수 있다.", factor: "FT"},
{question: "가까운 사람들과의 관계에 많은 시간과 노력을 투자한다.", factor: "FT"},
{question: "타인과의 갈등을 해결할 때, 감정적인 면을 우선적으로 고려한다.", factor: "FT"},
{question: "주변 사람들의 감정에 민감하게 반응한다.", factor: "FT"},
{question: "개인적인 가치와 믿음을 중요하게 생각하며, 이를 기반으로 판단을 내린다.", factor: "FT"},
{question: "상황에 따라 융통성 있게 대처하는 것을 선호하며, 감정의 영향을 받기 쉽다.", factor: "FT"},
{question: "새로운 아이디어를 도입하는 것보다는 이미 검증된 방법을 선호한다.", factor: "JP"}
{question: "일정을 잘 관리하고, 계획에 따라 일을 처리하는 것을 중요하게 생각한다.", factor: "JP"}
{question: "결정을 내린 후에는 그 결정에 따라 행동하는 것을 선호한다.", factor: "JP"}
{question: "프로젝트를 시작할 때부터 마무리까지 철저한 계획을 세우는 것을 좋아한다.", factor: "JP"}
{question: "일 처리에 있어서 체계적이고 조직적인 방식을 선호한다.", factor: "JP"}
{question: "계획을 세운 후에는 그대로 따르는 것이 가장 효율적이라고 생각한다.", factor: "JP"}
{question: "무작정 시작하기보다는 모든 것을 철저하게 준비한 후에 시작하는 것을 선호한다.", factor: "JP"}
{question: "결과에 대한 예측과 목표 달성을 위해 세부 계획을 세우는 것을 중요하게 생각한다.", factor: "JP"}
{question: "약속이나 일정을 엄수하며, 마감 기한을 정확하게 지키는 것에 큰 가치를 둔다.", factor: "JP"}
{question: "변동이 싫어 일정한 패턴과 순서에 따라 일을 진행하는 것을 좋아한다.", factor: "JP"}
]
